services:
    app.redirect_exception_listener:
        class: davidwnek\RedirectAccessControlBundle\EventListener\AccessDeniedListener
        arguments: [ '@router', '%redirect_access_control.redirects%' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }